package com.mybatis.dao;

import com.mybatis.model.StudentCard;
import com.mybatis.model.StudentCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    long countByExample(StudentCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int deleteByExample(StudentCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int insert(StudentCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int insertSelective(StudentCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    List<StudentCard> selectByExample(StudentCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    StudentCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") StudentCard record, @Param("example") StudentCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int updateByExample(@Param("record") StudentCard record, @Param("example") StudentCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int updateByPrimaryKeySelective(StudentCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int updateByPrimaryKey(StudentCard record);
}