package com.mybatis.dao;

import com.mybatis.model.StudentClass;
import com.mybatis.model.StudentClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    long countByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int deleteByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int insert(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int insertSelective(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    List<StudentClass> selectByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    StudentClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") StudentClass record, @Param("example") StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int updateByExample(@Param("record") StudentClass record, @Param("example") StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int updateByPrimaryKeySelective(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    int updateByPrimaryKey(StudentClass record);
}