package com.mybatis.model;

import java.io.Serializable;

public class StudentClass implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_class.id
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_class.class_name
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_class
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_class.id
     *
     * @return the value of student_class.id
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_class.id
     *
     * @param id the value for student_class.id
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_class.class_name
     *
     * @return the value of student_class.class_name
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_class.class_name
     *
     * @param className the value for student_class.class_name
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }
}