package com.mybatis.model;

import java.io.Serializable;

public class StudentCard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_card.id
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_card.number
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_card
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_card.id
     *
     * @return the value of student_card.id
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_card.id
     *
     * @param id the value for student_card.id
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_card.number
     *
     * @return the value of student_card.number
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_card.number
     *
     * @param number the value for student_card.number
     *
     * @mbg.generated Mon Mar 30 20:59:06 CST 2020
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }
}